overblog_graphql:
    definitions:
        schema:
            query: Query
        builders:
            args:
                Pager: "App\\GraphQL\\Args\\Pager"
                PastaFilter: "App\\GraphQL\\Args\\PastaFilter"
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
